<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php echo $this->title ?></title>
    <style type='text/css'>
        html,body {
            margin: 0;
            padding: 0;
            height: 100%;
        }
        .header,
        .columns,
        .column-1-2 {
            box-sizing: border-box;
            display: block;
            float: left;
            width: 100%;
            height: 100%;
            padding: 0 20px;
        }        
        .header {
            position:fixed;
            top: 0;
            background: #eee;
            border-bottom: solid 1px #555;
            height: auto;
        }
        .columns {
            padding-top: 80px;
            padding-bottom: 10px;
        }
        .column-1-2 {
            padding: 0;
            width: 50%;
        }        
        .column-1-2 textarea {
            width: 100%;
            height: 100%;
            min-height: 400px;
            border: solid 1px #999;
        }
    </style>
</head>
<body>

<div class='header'>
    <h1><?php echo $this->title ?> <a style='float:right' href='<?php echo $this->url ?>' target='_blank'><?php echo $this->url ?></a></h1>
</div>
