<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php echo $this->title ?></title>
    <style type='text/css'>
        html,body {
            margin: 0;
            padding: 0;
            height: 100%;
        }
        .header,
        .columns,
        .column-1-2 {
            display: block;
            float: left;
            width: 100%;
            height: 100%;
        }        
        .header {
            background: #eee;
            border-bottom: solid 1px #555;
            height: auto;
        }
        .column-1-2 {
            width: 50%;
        }        
        .column-1-2 iframe {
            width: 100%;
            height: 100%;
            min-height: 400px;
            border: solid 1px #555;
        }
    </style>
</head>
<body>

<div class='header'>
    <h1><?php echo $this->title ?></h1>
    <h2>Original: <a href='<?php echo $this->url ?>' target='_blank'><?php echo $this->url ?></a></h2>
</div>
